
### Create a new order
POST http://localhost:5172/api/localhost:5172/api/orders/1
Content-Type: application/json

{ 
    "id": 1,
    "Title": "The Great Gatsby",
    "Author": "F. Scott Fitzgerald",
    "PublishedDate": "1925-04-10"
}

###

### Update an order
PUT http://localhost:5172/api/orders/1
Content-Type: application/json

{   "id": 1,
     "Title": "The Great Gatsby",
     "Author": "F. Scott Fitzgerald",
    "PublishedDate": "1925-04-10"
}
    


 GET http://localhost:5172/api/orders/1
Accept: application/json        
{
    "id": 1,
    "Title": "The Great Gatsby",
    "Author": "F. Scott Fitzgerald",
    "PublishedDate": "1925-04-10"
}

###

### Delete an order
DELETE http://localhost:5172/api/orders/1
Accept: application/json

###