### Get all books
GET http://localhost:5000/api/books
Accept: application/json

###

### Get order by ID
GET http://localhost:5000/api/books/1
Accept: application/json

###

### Create a new order
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "id": 98,
  "title": "Graf monter krista",
  "author": "Jon lll",
  "price": 20.99,
  "publishedDate": "2000-10-04T00:00:00Z"
}

###

### Update an order
PUT http://localhost:5000/api/books/1
Content-Type: application/json

{    
    "title": "Graf monter krista",
    "author": "Jon kkk",
    "price": 39.99,
    "publishedDate": "2025-10-04T00:00:00Z"
}

###

### Delete an order
DELETE http://localhost:5000/api/books/1
Accept: application/json